defaults:
  logdir: "log/log_dir"
  traindir: "log/train_dir"
  evaldir: "log/eval_dir"
  offline_traindir: "log/offline/train_dir"
  offline_evaldir: "log/offline/eval_dir"
  datetime: ""
  dataset_size: 1000000
  seed: 0
  deterministic_run: False
  steps: 1.0
  eval_every: 10000.0
  log_every: 1000.0
  log_scalars: True
  log_images: True
  log_videos: True
  reset_every: 0
  gpu_growth: True
  precision: 32
  parallel: False
  obs_type: "lidar"
  # Environment
  envs: 1
  track: "austria"
  task: "max_progress"
  action_repeat: 4
  eval_episodes: 5
  time_limit_train: 2000
  time_limit_test: 4000
  prefill_agent: "gap_follower"
  prefill: 5000
  eval_noise: 0.0
  clip_rewards: "none"
  clip_rewards_min: -1
  clip_rewards_max: 1
  # Model
  encoded_obs_dim: 1080
  deter_size: 200
  stoch_size: 30
  num_units: 400
  reward_out_dist: "normal"
  dense_act: "elu"
  cnn_act: "relu"
  pcont: True
  free_nats: 3.0
  kl_scale: 1.0
  pcont_scale: 10.0
  weight_decay: 0.0
  weight_decay_pattern: ".*"
  expl_until: 0
  # Training
  batch_size: 50
  batch_length: 50
  train_ratio: 512
  train_every: 1000
  train_steps: 100
  pretrain: 100
  model_lr: 0.0006
  value_lr: 0.00008
  actor_lr: 0.00008
  grad_clip: 1.0
  dataset_balance: False
  # Behavior
  discount: 0.99
  disclam: 0.95
  horizon: 15
  action_dist: "tanh_normal"
  action_init_std: 5.0
  expl: "additive_gaussian"
  expl_amount: 0.3
  expl_decay: 0.0
  expl_min: 0.3
